// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAh2xxj2Ot9-8v-PNwf5W5f2-hcp4zpg_Q',
    appId: '1:1039969809797:web:d41a139df64391e47000ec',
    messagingSenderId: '1039969809797',
    projectId: 'flutter-train-app-1',
    authDomain: 'flutter-train-app-1.firebaseapp.com',
    storageBucket: 'flutter-train-app-1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8jOwD585T0QaHUYGtVpsUjRPvF8EUKFQ',
    appId: '1:1039969809797:android:289dcfefbf7f01e67000ec',
    messagingSenderId: '1039969809797',
    projectId: 'flutter-train-app-1',
    storageBucket: 'flutter-train-app-1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALEqb7kVxDi084lOOGOV_kpEPPo2Efvts',
    appId: '1:1039969809797:ios:5e58f2029b5ab1d47000ec',
    messagingSenderId: '1039969809797',
    projectId: 'flutter-train-app-1',
    storageBucket: 'flutter-train-app-1.appspot.com',
    iosClientId: '1039969809797-2e0uvs2iqrihmf0a7r7qcpsnmp6ns9gr.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALEqb7kVxDi084lOOGOV_kpEPPo2Efvts',
    appId: '1:1039969809797:ios:898be1d46630025b7000ec',
    messagingSenderId: '1039969809797',
    projectId: 'flutter-train-app-1',
    storageBucket: 'flutter-train-app-1.appspot.com',
    iosClientId: '1039969809797-7jkm3rq8lc7d643slj8oplht75inamgg.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
